# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.8.8.post604+gc212e011 on Mon Sep 20 09:36:29 2021
# Model: Habitat Quality

import logging
import sys

import natcap.invest.habitat_quality
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = {
    'access_vector_path': 'C:/Users/bb8/Documents/INVEST17/accessibility.shp',
    'half_saturation_constant': '.5',
    'lulc_cur_path': 'C:/Users/bb8/Documents/INVEST17/lulce_deg_sbn51.tif',
    'results_suffix': '',
    'sensitivity_table_path': 'C:/Users/bb8/Documents/INVEST17/sensibility_t.csv',
    'threats_table_path': 'C:/Users/bb8/Documents/INVEST17/threats_t.csv',
    'workspace_dir': 'C:/Users/bb8/Documents/INVEST17/OUTPUT/lulce_deg_sbn51',
}

if __name__ == '__main__':
    natcap.invest.habitat_quality.execute(args)
